version: "3.3"

services:
  geth-node:
    build:
      context: .
      args:
        - goversion=1.15.2
        - gethversion=v1.9.25
        - gohost=linux-amd64.tar.gz
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./data:/app/data
    # command: ls data
    # command: bash -c "geth init --datadir ./data privatechain.json && ls"
    # command: bash -c "geth init --datadir ./data privatechain.json && geth --networkid 5333 --datadir ./data --nodiscover --http --http.port "8545" --port "30303" --http.corsdomain "*" --http.addr "0.0.0.0" --http.api="eth,net,personal,web3,debug,admin,miner" --ipcdisable"
    # command: geth --networkid 5333 --datadir ./data --nodiscover --http --http.port "8545" --port "30303" --http.corsdomain "*" --http.addr "0.0.0.0" --http.api="eth,net,personal,web3,debug,admin,miner" --ipcdisable
    command: bash run.sh privatechain-data privatechain
