version: "3.3"

services:
  geth-node:
    build:
      context: .
      args:
        - goversion=1.15.2
        - gethversion=v1.9.25
        - gohost=linux-amd64.tar.gz
    ports:
      # Make sure that the ports match the ones you pass to the run.sh script
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ./data:/app/data
    # arg1: data folder, arg2: config file, arg3: http port, arg4: port for peers, arg5: network/chain ID
    command: bash run.sh privatechain-data privatechain 8545 30303 9999
