version: "3.3"

services:
  geth-node:
    build:
      context: .
      args:
        - goversion=1.15.2
        - gethversion=v1.9.25
        - gohost=linux-amd64.tar.gz
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./data:/app/data
    command: bash run.sh privatechain-data privatechain
